#
# This file contains configuration flags to customize Bronte Sihan Li's website on Github
#

# Name of your site (displayed in the header)
name: DREAM 2023 | Improving Wildfire Prediction and Vegetation Recovery Modeling with Explainable AI

# Short bio or description (displayed in the header)
description: This is the project site for wildfire modeling by Bronte Sihan Li, MLS(ASCP). You can find project descriptions, documentation and useful links here. This site will be continuously updated throughout the duration of the project.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://bronteee.github.io/images/headshot.JPG

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: li.siha [at] northeastern [dot] edu
  linkedin: https://www.linkedin.com/in/brontesihanli/
  rss: # just type anything here for a working RSS icon

# Your website URL (e.g. http://ajstent.github.io)
# Used for Sitemap.xml and your RSS feed
url: https://bronteee.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/



# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman

background-image: url('/images/background.jpeg')
